sonar.projectKey=mon-projet
sonar.projectName=Mon projet test feature
sonar.projectVersion=1.0
sonar.sources=src/test/kotlin
sonar.host.url=http://localhost:9000
sonar.token=sqa_96a8837d1e05146328a238a121acb7c37a3cde6d
sonar.kotlin.android=true